---
driver:
  name: vagrant

transport:
  max_ssh_sessions: 5


provisioner:
  name: ansible_playbook
  hosts: all
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbose: true
  ansible_diff: true
  hosts: all


platforms:
  - name: centos-7.2
    driver_config:
      box: bento/centos-7.2

verifier:
  name: inspec
  inspec_tests:
    - https://github.com/FXinnovation/BN-LinuxHardening-Tests

suites:
  - name: default
    provisioner: ansible_playbook
    playbook: default.yml
    additional_copy_path:
      - "."
