---
- name: "Configure PAM"
  copy: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'pam.d/su', dest: '/etc/pam.d/su' }
    - { src: 'pam.d/system-auth', dest: '/etc/pam.d/system-auth' }
    - { src: 'pam.d/passwd', dest: '/etc/pam.d/passwd' }
