---
- name: install rsyslog
  yum: name=rsyslog state=latest

- name: 'stop syslog'
  systemd: state=stopped enabled=no name='syslog'
  register: command_result
  failed_when: "command_result|failed and 'Could not find the requested service' not in command_result.msg"

- name: 'start rsyslog'
  systemd: state=started enabled=yes name='rsyslog'


- name: "Install new rsyslog.conf"
  copy: src="rsyslog.conf" dest="/etc/rsyslog.conf" owner=root group=root mode=0644
  notify:
    - restart rsyslog
