---
- name: Cron Configuration files ownership
  file: path='{{item}}' owner=root group=root mode=0600
  with_items:
    - /etc/anacrontab
    - /etc/crontab
    - /etc/cron.hourly
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly

- name: Cron Configuration Directory ownership
  file: path=/etc/cron.d owner=root group=root mode=0700

- name: Passwd  / group file security
  file: path='{{item}}' owner=root group=root mode=0644
  with_items:
    - /etc/passwd
    - /etc/group

- name: shadow file security
  file: path='{{item}}' owner=root group=root mode=0600
  with_items:
    - /etc/shadow
    - /etc/gshadow

- name: find world writeable files
  shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002"
  changed_when: False
  check_mode: no
  register: world_writeable_files

- name: remove world writeable bit
  file: path='{{item}}' mode="o-w"
  with_items: '{{ world_writeable_files.stdout_lines }}'

- name: "Verify No Legacy \"+\" Entries Exist in user/group identity files"
  lineinfile: dest='{{item}}' regexp="^\+:" state=absent
  with_items:
    - /etc/passwd
    - /etc/shadow
    - /etc/group

- name: "get all accounts with uid 0"
  shell: awk -F'':'' '($3 == 0) { print $1 }' /etc/passwd removes=/etc/passwd 
  changed_when: False
  check_mode: no
  register: uid_0_accounts

- name: "Delete UID 0 Accounts Other Than root."
  user: name='{{ item }}' state=absent force=yes
  with_items: "{{ uid_0_accounts.stdout_lines | difference(['root']) }}"

- name: "Set Daemon mask to 027"
  lineinfile: dest=/etc/sysconfig/init line="umask 027" regexp="^umask"

- name: "add umask to profile"
  copy: src="umask.sh" dest="/etc/profile.d/umask.sh" owner=root group=root mode=0644 

- name: "replace all instances of umask in /etc/bashrc to umask 077"
  replace:
    dest: /etc/bashrc
    regexp: '(\s+)umask.*?$'
    replace: '\1umask 077'

- name: "Remove OS Information from Login Warning Banners"
  replace: dest="{{item}}" regexp="{{ '\\\\' }}[mrsv]" replace=""
  with_items:
    - "/etc/issue"
    - "/etc/issue.net"
    - "/etc/motd"

- name: "Set proper permissions on the GRUB configuration file."
  file: path=/boot/grub2/grub.cfg owner=root group=root mode=0600

- name: "Set Password minimum day to 1"
  lineinfile: dest=/etc/login.defs regexp=^PASS_MIN_DAYS line="PASS_MIN_DAYS 1"

- name: "Set Password maximum day to 90"
  lineinfile: dest=/etc/login.defs regexp=^PASS_MAX_DAYS line="PASS_MAX_DAYS 90"

- name: "Modify Password quality file to be compliant with the bank."
  lineinfile: dest=/etc/security/pwquality.conf regexp={{ item.regex }} line={{ item.line }}
  with_items:
    - { regex: '^minlen', line: 'minlen = 8' }
    - { regex: '^dcredit', line: 'dcredit = 1' }
    - { regex: '^ucredit', line: 'ucredit = 1' }
    - { regex: '^ocredit', line: 'ocredit = 1' }
    - { regex: '^lcredit', line: 'lcredit = 1' }
    - { regex: '^minclass', line: 'minclass = 4' }

- stat:
    path: /var/spool/cron/root
  register: root_crontab

- name: Make sure root's crontab is owned by root
  file: name=/var/spool/cron/root owner=root group=root mode=600
  when: root_crontab.stat.exists == True

- name: Find World-Writable Directories
  shell: df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type d \( -perm -0002 -a ! -perm -1000 \) 2>/dev/null
  changed_when: False
  check_mode: no
  register: world_directories

- name: Set Sticky Bit on All World-Writable Directories
  file: path='{{item}}' mode="a+t"
  with_items: '{{ world_directories.stdout_lines }}'

- name: Disable interactive startup
  replace: dest=/etc/sysconfig/init regexp=^PROMPT=.* replace=PROMPT=no

- name: Require Authentication for Single-User Mode
  lineinfile: dest=/etc/sysconfig/init regexp=^SINGLE= line=SINGLE=sulogin