---
- name: Cron Configuration files ownership
  file: path='{{item}}' owner=root group=root mode=0600
  with_items:
    - /etc/anacrontab
    - /etc/crontab
    - /etc/cron.hourly
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly

- name: Cron Configuration Directory ownership
  file: path=/etc/cron.d owner=root group=root mode=0700

- name: Passwd  / group file security
  file: path='{{item}}' owner=root group=root mode=0644
  with_items:
    - /etc/passwd
    - /etc/group

- name: shadow file security
  file: path='{{item}}' owner=root group=root mode=0600
  with_items:
    - /etc/shadow
    - /etc/gshadow

- name: find world writeable files
  shell: "df --local -P | awk {\'if (NR!=1) print $6\'} | xargs -I \'{}\' find \'{}\' -xdev -type f -perm -0002"
  changed_when: False
  check_mode: no
  register: world_writeable_files

- name: remove world writeable bit
  file: path='{{item}}' mode="o-w"
  with_items: '{{ world_writeable_files.stdout_lines }}'

- name: "Verify No Legacy \"+\" Entries Exist in user/group identity files"
  lineinfile: dest='{{item}}' regexp="^\+:" state=absent
  with_items:
    - /etc/passwd
    - /etc/shadow
