---
- hosts: all
  tasks:
    - name: "Software Updates: Verify that gpgcheck is activated"
      lineinfile: dest=/etc/yum.conf regexp=^gpgcheck= line=gpgcheck=1
    - name: Update all packages
      yum: name=* state=latest
    - name: "Grub.cfg permissions and owner"
      file: path=/boot/grub2/grub.cfg owner=root group=root mode=0600
    - name: "Restrict Core Dumps /etc/security/limits.conf"
      lineinfile: dest=/etc/security/limits.conf line="* hard core 0"
    - name: "Restrict Core Dumps /etc/sysctl.conf"
      lineinfile: dest=/etc/sysctl.conf line="fs.suid_dumpable = 0"
    - name: "Configure ExecShield"
      lineinfile: dest=/etc/sysctl.conf line="kernel.exec-shield = 1"
    - name: "Enable Randomized Virtual Memory Region Placement"
      lineinfile: dest=/etc/sysctl.conf line="kernel.randomize_va_space = 2"
    - name: "Disable unsecure services"
      systemd: name={{item}} state=stopped enabled=no masked=yes
      register: command_result
      failed_when: "command_result|failed and 'Could not find the requested service' not in command_result.msg"
      with_items:
        - "chargen-dgram"
        - "chargen-stream"
        - "daytime-dgram"
        - "daytime-stream"
        - "echo-dgram"
        - "echo-stream"
        - "tcpmux-server"
        - "avahi-daemon"
        - "cups"
        - "cups-lpd"
        - "nfslock"
        - "rpcgssd"
        - "rpcbind"
        - "rpcidmapd"
        - "rpcsvcgssd"
        - "syslog"
    - name: "Remove telnet-server"
      yum: name="telnet-server" state=removed
    - name: "Remove telnet client"
      yum: name="telnet" state=removed
    - name: "Remove gcc"
      yum: name="gcc" state=removed
    - name: "Remove cmake"
      yum: name="cmake" state=removed
    - name: "Remove rsh-server"
      yum: name="rsh-server" state=removed
    - name: "Remove rsh"
      yum: name="rsh" state=removed
    - name: "Remove rlogin"
      yum: name="rlogin" state=removed
    - name: "Remove NIS Client"
      yum: name="ypbind" state=removed
    - name: "Remove NIS Server"
      yum: name="ypserv" state=removed
    - name: "Remove tftp"
      yum: name="tftp" state=removed
    - name: "Remove tftp-server"
      yum: name="tftp-server" state=removed
    - name: "Remove talk"
      yum: name="talk" state=removed
    - name: "Remove talk-server"
      yum: name="talk-server" state=removed
    - name: "Remove xinetd"
      yum: name="xinetd" state=removed
    - name: "Remove LDAP server"
      yum: name="openldap-servers" state=removed
    - name: "Disable vsftpd"
      yum: name="vsftpd" state=removed
    - name: "Disable httpd"
      yum: name="httpd" state=removed
    - name: "Remove DHCP Server"
      yum: name="dhcp" state=removed
    - name: "Remove X Window server: change systemd default.target"
      file: path=/etc/systemd/system/default.target src=/usr/lib/systemd/system/multi-user.target state=link
    - name: "Remove X Window server: remove xorg-x11-server-common package"
      yum: name="xorg-x11-server-common" state=removed
    - name: "Disable IP Forwarding"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.ip_forward parameter = 0"
    - name: "Disable Send Packet Redirects (all)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.all.send_redirects = 0"
    - name: "Disable Send Packet Redirects (default)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.default.send_redirects = 0"
    - name: "Disable Source Routed Packet Acceptance (all)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.all.accept_source_route = 0"
    - name: "Disable Source Routed Packet Acceptance (default)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.default.accept_source_route = 0"
    - name: "Disable ICMP Redirect Acceptance (all)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.all.accept_redirects = 0"
    - name: "Disable ICMP Redirect Acceptance (default)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.default.accept_redirects = 0"
    - name: "Disable Secure ICMP Redirect Acceptance (all)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.all.secure_redirects = 0"
    - name: "Disable Secure ICMP Redirect Acceptance (default)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.default.secure_redirects = 0"
    - name: "Enable Bad Error Message Protection"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.icmp_ignore_bogus_error_responses = 1"
    - name: "Enable TCP SYN cookies"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.tcp_syncookies = 1"
    - name: "Enable RFC-recommended Source Route Validation (all)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.all.rp_filter = 1"
    - name: "Enable RFC-recommended Source Route Validation (default)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.default.rp_filter = 1"
    - name: "Enable Ignore Broadcast Requests"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.icmp_echo_ignore_broadcasts = 1"
    - name: "Log Suspicious Packets (all)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.all.log_martians = 1"
    - name: "Log Suspicious Packets (default)"
      lineinfile: dest=/etc/sysctl.conf line="net.ipv4.conf.default.log_martians = 1"
    - name: "Install rsyslog"
      yum: name="rsyslog" state=latest
    - name: "Install new rsyslog.conf"
      copy: src="templates/etc/rsyslog.conf" dest="/etc/rsyslog.conf" owner=root group=root mode=0644
    - name: "Enable and reload rsyslog"
      systemd: name="rsyslog" enabled=yes state=restarted masked=no
    - name: "Secure log files"
      file: path={{item}} owner=root group=root mode=0640 state=touch
      with_items:
        - "/var/log/secure"
        - "/var/log/kern.log"
        - "/var/log/daemon.log"
        - "/var/log/syslog"
        - "/var/log/unused.log"
    - name: "Install new sshd_config"
      copy: src="templates/etc/ssh/sshd_config" dest="/etc/ssh/sshd_config" owner=root group=root mode=0600
    - name: "Get password hashing algorithm"
      shell: "authconfig --test | grep 'password hashing algorithm is sha512'"
      register: authconfig_result
      ignore_errors: True
    - name: "Define Password hashing algorithm to sha512"
      command: "authconfig --passalgo=sha512 --update"
      when: authconfig_result.rc != 0
    - name: "pam_pwquality in /etc/pam.d/passwd"
      lineinfile: dest=/etc/pam.d/passwd line="password required pam_pwquality.so try_first_pass retry=5"
    - name: "pam_pwquality in /etc/security/pwquality.conf"
      lineinfile: dest=/etc/pam.d/passwd line="minlen=8 dcredit=1 ucredit=1 ocredit=1 lcredit=1 minclass=4"
    - name: "Lock account after 5 failed attempts (/etc/pam.d/password-auth)"
      lineinfile: dest=/etc/pam.d/password-auth line="{{item}}"
      with_items:
        - "auth required pam_env.so"
        - "auth required pam_faillock.so preauth audit silent deny=5 even_deny_root unlock_time=604800"
        - "auth [success=1 default=bad] pam_unix.so"
        - "auth [default=die] pam_faillock.so authfail audit deny=5 even_deny_root unlock_time=604800"
        - "auth sufficient pam_faillock.so authsucc audit deny=5 even_deny_root unlock_time=604800"
        - "auth required pam_deny.so"
    - name: "Lock account after 5 failed attempts (/etc/pam.d/system-auth)"
      lineinfile: dest=/etc/pam.d/system-auth line="{{item}}"
      with_items:
        - "auth required pam_env.so"
        - "auth required pam_faillock.so preauth audit silent deny=5 even_deny_root unlock_time=604800"
        - "auth [success=1 default=bad] pam_unix.so"
        - "auth [default=die] pam_faillock.so authfail audit deny=5 even_deny_root unlock_time=604800"
        - "auth sufficient pam_faillock.so authsucc audit deny=5 even_deny_root unlock_time=604800"
        - "auth required pam_deny.so"
        - "password sufficient pam_unix.so remember=4"
    - name: "Restrict Access to the su Command"
      lineinfile: dest=/etc/pam.d/su line="auth required pam_wheel.so use_uid"
    - name: "Set Password Expiration Days to 90"
      lineinfile: dest=/etc/login.defs regexp=^PASS_MAX_DAYS line="PASS_MAX_DAYS 90"
    - name: "Set Password minimum day to 1"
      lineinfile: dest=/etc/login.defs regexp=^PASS_MIN_DAYS line="PASS_MIN_DAYS 1"
    - name: "Disable System Accounts"
      script: scripts/disable_system_accounts.sh
    - name: "Set User/Group Owner and Permission on cron files"
      file: path="{{item}}" owner=root group=root mode=0600
      with_items:
        - "/etc/anacrontab"
        - "/etc/crontab"
        - "/etc/cron.hourly"
        - "/etc/cron.daily"
        - "/etc/cron.weekly"
        - "/etc/cron.monthly"
        - "/etc/cron.d"
    - name: "Set User/Group Owner and Permission on passwd file"
      file: path=/etc/passwd owner=root group=root mode=0644
    - name: "Set User/Group Owner and Permission on group file"
      file: path=/etc/group owner=root group=root mode=0644
    - name: "Set User/Group Owner and Permission on shadow file"
      file: path=/etc/shadow owner=root group=root mode=0600
    - name: "Set User/Group Owner and Permission on gshadow file"
      file: path=/etc/gshadow owner=root group=root mode=0600
    - name: "Get world writable files"
      shell: "df --local -P | awk {'if (NR!=1) print $6'} | xargs -I '{}' find '{}' -xdev -type f -perm -0002"
      register: world_writable_files
    - name: "Remove access to others on world writable file"
      file: path="{{item}}" mode="o-w"
      with_items: "{{ world_writable_files.stdout_lines }}"
    - name: "Verify No Legacy \"+\" Entries Exist in user/group identity files"
      lineinfile: dest={{item}} regexp="^\+:" state=absent
      with_items:
        - "/etc/passwd"
        - "/etc/shadow"
        - "/etc/group"
    - name: "Download samhain"
      get_url:
        url: "http://www.la-samhna.de/samhain/samhain-current.tar.gz"
        dest: /root/samhain-current.tar.gz
        checksum: sha256:6b2db91fc92b3a9fc2edcc6ee16438156753c05f69c114856289e9f25ba0e50a
    - name: "Remove old sources"
      file: path=/root/src state=absent
    - name: "Create /root/src"
      file: path=/root/src state=directory
    - name: "Extract samhain sources"
      unarchive: src=/root/samhain-current.tar.gz remote_src=yes dest=/root/src
    - name: "Build samhain 4.2.0 rpm"
      command: echo rpmbuild -ta /root/src/samhain-4.2.0.tar.gz
    - name: "Set Daemon umask"
      lineinfile: dest=/etc/sysconfig/init line="umask 027"
    - name: "Set Default umask for Users"
      lineinfile: dest=/etc/profile.d/custom.sh line="umask 077" state=present create=yes
    - name: "Remove OS Information from Login Warning Banners"
      lineinfile: dest="{{item}}" regexp="\\m|\\r|\\s|\\S|\\v" state=absent
      with_items:
        - "/etc/issue"
        - "/etc/issue.net"
        - "/etc/motd"









